# Generated by Django 5.0.3 on 2024-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_status_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
