# Generated by Django 5.0.3 on 2024-03-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_duty_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
